## Beispiel Transformer Forward-Path

In [ ]:
import numpy as np

#### 1. Word Embeddings

vereinfachte Annahme: 3 Wörder mit einer Embedding-Dimension n=4

In [30]:
DIM_EMB = 4
vocab = ["Tim", "isst", "Pizza"]
np.random.seed(42)
word_embeddings = np.random.randn(len(vocab), DIM_EMB)  # 3 Wörter, 4-dimensionale Embeddings zufällig generiert

print("Word embeddings für:")
for i in range(len(vocab)):
    print(f"{vocab[i]}: {word_embeddings[i]}")

Word embeddings für:
Tim: [ 0.49671415 -0.1382643   0.64768854  1.52302986]
isst: [-0.23415337 -0.23413696  1.57921282  0.76743473]
Pizza: [-0.46947439  0.54256004 -0.46341769 -0.46572975]


#### 2. Positional Encoding

Als Funktionen nutzen wir:
1) sin(x)
2) sin(0.5x)
3) sin(0.25x)
4) sin(0.1x)

In [45]:
from math import sin

pos_enc = []
for i in range(len(vocab)):
    emb_pos = [sin(i), sin(0.5*i), sin(0.25*i), sin(0.1*i)]
    emb_pos = np.array(emb_pos)
    pos_enc.append(emb_pos + word_embeddings[i].tolist())
    print(f"Embedding Position für Position {vocab[i]}: {emb_pos}")

pos_enc = np.array(pos_enc)
print("\npos_enc:", pos_enc)

Embedding Position für Position Tim: [0. 0. 0. 0.]
Embedding Position für Position isst: [0.84147098 0.47942554 0.24740396 0.09983342]
Embedding Position für Position Pizza: [0.90929743 0.84147098 0.47942554 0.19866933]

pos_enc: [[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [ 0.60731761  0.24528858  1.82661677  0.86726815]
 [ 0.43982304  1.38403103  0.01600785 -0.26706042]]


#### 3. Attention

für unsere Gewichtsmatrizen Q, K, V nehmen wir Zufallswerte in einem richtigen System werden diese trainiert

In [ ]:
W_Q = np.random.randn(4, 4)
W_K = np.random.randn(4, 4)
W_V = np.random.randn(4, 4)

In [51]:
# Query, Key, Value Berechnung für jedes Wort
Q = []
K = []
V = []
for i in range(len(vocab)):
    Q.append(pos_enc[i] @ W_Q)  # @ ist Matrixmultiplikation
    K.append(pos_enc[i] @ W_K)
    V.append(pos_enc[i] @ W_V)

In [96]:
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

In [103]:
attention_outputs = []

for i in range(len(vocab)):
    sim_values = []
    for j in range(len(vocab)):
        sim_values.append(np.dot(Q[i], K[j]))
    sim_values = softmax(sim_values)
    attention_outputs.append(sim_values @ V)

attention_outputs = np.array(attention_outputs)
print("Attention Outputs:", attention_outputs)

Attention Outputs: [[-2.77686381 -0.02117811  1.96634547  3.0930654 ]
 [-2.77593784 -0.02201525  1.96545112  3.09191451]
 [-2.38342117 -0.38805297  1.69225008  2.61463683]]


#### 4. Residual Connection

In [104]:
residual_output = attention_outputs + pos_enc
print("Residual Output:", residual_output)

Residual Output: [[-2.28014966 -0.15944241  2.61403401  4.61609525]
 [-2.16862023  0.22327333  3.7920679   3.95918266]
 [-1.94359813  0.99597805  1.70825792  2.34757641]]


#### Zusammenfassung

In [105]:

print("Word Embeddings:\n", word_embeddings)
print("\nInput mit Positional Encoding:\n", pos_enc)
print("\nAttention Output:\n", attention_outputs)
print("\nOutput nach Residual Connection:\n", residual_output)


Word Embeddings:
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]]

Input mit Positional Encoding:
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [ 0.60731761  0.24528858  1.82661677  0.86726815]
 [ 0.43982304  1.38403103  0.01600785 -0.26706042]]

Attention Output:
 [[-2.77686381 -0.02117811  1.96634547  3.0930654 ]
 [-2.77593784 -0.02201525  1.96545112  3.09191451]
 [-2.38342117 -0.38805297  1.69225008  2.61463683]]

Output nach Residual Connection:
 [[-2.28014966 -0.15944241  2.61403401  4.61609525]
 [-2.16862023  0.22327333  3.7920679   3.95918266]
 [-1.94359813  0.99597805  1.70825792  2.34757641]]
